[package]
name = "gha-version-test"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
reqwest = { version = "0.12.7", default-features = false, features = [
  "json",
  "rustls-tls",
] }
tokio = { version = "1.40.0", features = ["full"] }
