name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-push-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      # Cache Docker layers
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /home/runner/.cache/docker
          key: ${{ runner.os }}-docker-${{ hashFiles('Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-docker-

      # Set short commit SHA
      - name: Set short commit SHA
        id: set_commit_sha
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      # Build image using cached layers
      - name: Build Docker image
        run: |-
          docker build \
            --cache-from=type=local,src=/home/runner/.cache/docker \
            --cache-to=type=local,dest=/home/runner/.cache/docker \
            -t scipio . &&
          docker tag scipio anish/scipio:${{ env.SHORT_SHA }}
        working-directory: .

      - name: Finish
        run: echo ${{ env.SHORT_SHA }}
