name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-push-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - name: Set short commit SHA
        id: set_commit_sha
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Install dependencies
        run: sudo apt-get install -y pkg-config libssl-dev

      - name: Run sccache
        uses: mozilla-actions/sccache-action@v0.0.5

      - name: Set SCCACHE environment variables
        run: |
          echo "SCCACHE_BUCKET=my-sccache-bucket" >> $GITHUB_ENV
          echo "RUSTC_WRAPPER=$(which sccache)" >> $GITHUB_ENV

      - name: Build image with sccache
        run: |-
          docker build \
            --build-arg RUSTC_WRAPPER=$(which sccache) \
            -t scipio . &&
          docker tag scipio anish/scipio:${{ env.SHORT_SHA }}
        working-directory: .

      - name: Finish
        run: echo ${{ env.SHORT_SHA }}
