name: CI

on:
  push:
    branches:
      - main

jobs:
  version-bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch full history for squashing

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install cargo-release
        run: cargo install cargo-release

      - name: Auto bump version
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          cargo release patch --execute --no-publish

      - name: Squash and push changes
        run: |
          # Get the original commit message
          ORIGINAL_COMMIT_MSG=$(git log -1 --pretty=%B)

          # Squash the previous commit (version bump)
          git reset --soft HEAD~1

          # Amend the commit with both the original commit message and the version bump
          git commit --amend -m "${ORIGINAL_COMMIT_MSG}" -m "chore: bump version to $(grep '^version' Cargo.toml | cut -d '"' -f2)"

          # Force push the changes
          git push --force-with-lease origin main
          git push origin --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
